faet: add main page
ClevertecFrontendLab/sprint1-HartanovichEV pull request #1
Opened 2023-01-24 10:38 UTC by HartanovichEV

2023-01-24 10:43 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 33.33333333333333%.
Общее количество тестов: 6.
Количество непройденных тестов: 4.
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674557005/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 320px -- test layout content view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674557005/Test%20width%20320px%20--%20test%20layout%20content%20view%20(failed).png)
***
**Test width 768px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674557005/Test%20width%20768px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 768px -- test layout content view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674557005/Test%20width%20768px%20--%20test%20layout%20content%20view%20(failed).png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674557005/book-page.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674557005/content-list.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674557005/content-window.png)

2023-01-24 11:41 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674560467/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674560467/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674560467/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674560467/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674560467/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674560467/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674560467/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674560467/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674560467/content-window.png)

2023-01-24 11:51 UTC, dariavorom requested changes

2023-01-24 11:51 UTC, dariavorom commented on src/pages/main/main-page.jsx
> +// if (document.documentElement.clientWidth < 321) {
закомментированного кода быть не должно, нужно пересмотреть по всем файлам

2023-01-24 11:51 UTC, dariavorom commented on .eslintrc.js
>          indent: 'off', // https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/indent.md
нету страницы деталей книги, не меняется раскладка отображения книг (список, плитка)

2023-01-24 11:55 UTC, Ivan6813 requested changes

2023-01-24 11:55 UTC, Ivan6813 commented on src/components/categories.jsx
> +    </ul>
списки лучше выводить через map. То есть создавать массив с данными и потом по этому массиву проходить map : array.map((item) => <li>{ item }</li>);

2023-01-24 11:55 UTC, Ivan6813 commented on src/components/footer.jsx
> +        </a>
пересмотри все места, где ты выводишь однотипные списки и используй там map

2023-01-28 10:24 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674901481/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674901481/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674901481/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674901481/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674901481/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674901481/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674901481/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674901481/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674901481/content-window.png)

2023-01-28 11:05 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674903903/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674903903/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674903903/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674903903/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674903903/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674903903/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674903903/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674903903/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674903903/content-window.png)

2023-01-28 15:07 UTC, Ivan6813 approved these changes

2023-01-28 17:17 UTC, dariavorom requested changes

2023-01-28 17:17 UTC, dariavorom commented on src/pages/main/main-page.jsx
> +// import { Documents } from '../../src/components/documents';
удалить закомментированный код по всем файлам

2023-01-28 17:17 UTC, dariavorom commented on src/src/components/blocks-books.jsx
> +      <BookCard ratingBg='No' rating='ещё нет оценок' />
создай папку constants, где ты будешь хранить данные. в ней создай файлик с переменной с данными книг и выводи BookBlock через BookBlock map. таким образом не будет дублирования кода

2023-01-28 17:17 UTC, dariavorom commented on src/src/components/categories.jsx
> +  const categories = [
это тоже в константы, компонент будет красивее, код чище

2023-01-28 17:17 UTC, dariavorom commented on src/src/components/footer.jsx
> +  const iconArray = [
тоже вынести

2023-01-28 17:17 UTC, dariavorom commented on src/src/scss/_variables.scss
> +// $container-width-mobile: 320px;
в стилях закомментированный не оставлять

2023-01-28 17:17 UTC, dariavorom commented on src/src/scss/app.scss
> +// .cart {
:-)

2023-01-29 06:38 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674974281/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674974281/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674974281/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674974281/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674974281/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674974281/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674974281/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674974281/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1674974281/content-window.png)

2023-01-29 06:59 UTC, dariavorom requested changes

2023-01-29 06:59 UTC, dariavorom commented on src/index.js
>  import ReactDOM from 'react-dom/client';
осталось поправить структуру файлов. у тебя в структуре в корне проекта должна быть папка src и  public (так и есть). но в папке src лежит еще одна папка src) это неверно. да еще и два файла index.js  с роутами
нужно из вложенной папка все перенести в родительную src

2023-01-29 06:59 UTC, dariavorom commented on src/src/components/books-section.jsx
> +import React from 'react';
импортировать React уже не нужно. сразу делай import { useState }  from 'react'
еще в других файлах поправить нужно

2023-01-29 17:26 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1675013194/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1675013194/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1675013194/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1675013194/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1675013194/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1675013194/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1675013194/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1675013194/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/HartanovichEV/1675013194/content-window.png)

2023-01-29 17:36 UTC, dariavorom approved these changes

2023-01-29 17:39 UTC, merged